[versions]
clikt = "3.5.2"
freemarker = "2.3.31"
jreleaser = "1.10.0"
kaml = "0.55.0" # Synced with Kobweb TODO: Remove after Kobweb turns this into an API dependency starting in 0.16.3
kobweb-cli = "0.9.15-SNAPSHOT"
kobweb-libs = "0.16.2"
kotter = "1.1.2"
kotlin = "1.8.10"
kotlinx-coroutines = "1.6.0"
okhttp = "4.10.0"
shadow = "7.0.0"

[libraries]
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
freemarker = { module = "org.freemarker:freemarker", version.ref = "freemarker" }
kaml = { module = "com.charleskorn.kaml:kaml", version.ref = "kaml" }
kobweb-common = { module = "com.varabyte.kobweb:kobweb-common", version.ref = "kobweb-libs" }
kotter = { module = "com.varabyte.kotter:kotter", version.ref = "kotter" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

[plugins]
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
